import type { Metadata } from 'next';

import '@/styles/globals.css';

import { auth } from '@/../auth';
import Provider from '@/trpc/Provider';
import { SessionProvider } from 'next-auth/react';

import { el_messiri } from '@/config/fonts';
import { ThemeProvider } from '@/components/site/theme-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <>
      <SessionProvider session={session}>
        <html lang="en" dir="rtl">
          <body className={el_messiri.className}>
            <ThemeProvider attribute="class" defaultTheme="light">
              <Provider>{children}</Provider>
            </ThemeProvider>
          </body>
        </html>
      </SessionProvider>
    </>
  );
}
